### ISSUE TITLE
TorchScript model -Failed to update context stat: [ 0] INVALID_ARG - Timer not set correctly.

### ISSUE THREAD

**Issue by daquilnp** [NVIDIA/triton-inference-server#1236]
**Description**
I made a TorchScript resnet model and put it the nvidia inference server. It will load successfully. Then I hit it with the Python API. It will work the 1 or 2 times, but then I will get the error 
`Failed to update context stat: [ 0] INVALID_ARG - Timer not set correctly.`
I am running the model with one batch of all zeros.

**TRTIS Information**
What version of TRTIS are you using? 20.02
Are you using the TRTIS container or did you build it yourself?
I am using the TRTIS container 20.02. And I clone branch r20.02 and built the client from that. I exported the model from Pytorch 1.4.0
**To Reproduce**
Steps to reproduce the behavior.

Heres the api call that I make within the client.py
```
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action="store_true", required=False, default=True,
                        help='Enable verbose output')
    parser.add_argument('-u', '--url', type=str, required=False, default='localhost:8000',
                        help='Inference server URL. Default is localhost:8000.')
    parser.add_argument('-i', '--protocol', type=str, required=False, default='http',
                        help='Protocol ("http"/"grpc") used to ' +
                        'communicate with inference service. Default is "http".')

    FLAGS = parser.parse_args()
    protocol = ProtocolType.from_str(FLAGS.protocol)
    
    model_name = "ts_feature_extraction"
    input_name = "INPUT__0"
    output_name = "OUTPUT__0"

    model_version = -1
    batch_size = 1

    # Create the inference context for the model.
    ctx = InferContext(FLAGS.url, protocol, model_name, model_version, FLAGS.verbose)
    input_batch = np.float32(np.zeros(shape=[3,64,200]))

    start_time = time.time()
    try:
      result = ctx.run(
                  { input_name : [input_batch] },
                  { output_name : (InferContext.ResultFormat.RAW) },
                  batch_size)
    except Exception as e:
      print (e)
      print ("exit sadly")
      exit()
    output0_data = result[output_name][0]
    
    print ("infer time: {}s".format(time.time()-start_time))
```

Heres the config
```
name: "ts_feature_extraction"
platform: "pytorch_libtorch"
max_batch_size : 500

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 64, 200 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 512, 1 ]
    
  } 
]
```

In the Server's log I get the following error
`I0326 22:38:56.834344 1 libtorch_backend.cc:805] CUDA driver error: a PTX JIT compilation failed` after 1 or 2 times running the torchscript model

In the Client log I get the following error:
```
 * We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< NV-InferResponse:
< NV-Status: code: INTERNAL msg: "failed to run model \'ts_feature_extraction_0_gpu1" server_id: "inference:0" request_id: 30
< Content-Type: application/octet-stream
< Content-Length: 0
<
* Connection #0 to host localhost left intact
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
[inference:0 30] failed to run model 'ts_feature_extraction_0_gpu1
```
**Expected behavior**
I expect it to work every time

Let me know if there is any other information I did not give. Thank you

**Comment by daquilnp** [comment]
I figured it out.
Looking more into the error  `CUDA driver error: a PTX JIT compilation failed`, I updated the nvidia drivers. Now it works every time without fail.
