### ISSUE TITLE
Trtsever crashes !!

### ISSUE THREAD

**Issue by whatdhack** [NVIDIA/triton-inference-server#1299]
**Description**
Seeing the following error on a Mask RCNN Tensorflow Saved Model. Using the Triton server container.

```
F tensorflow/stream_executor/cuda/cuda_dnn.cc:535] Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: {count: 1 feature_map_count: 64 spatial: 0 25 value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
```

However, if I send an incorrect sized array, I get an error mesage and the trtserver does not crash .

```
I0410 16:33:36.387566 888 model_repository_manager.cc:511] GetInferenceBackend() 'modelx' version -1
I0410 16:33:36.387604 888 http_server.cc:1214] Infer failed: unexpected shape for input 'image:0' for model 'modelx'. Expected [-1,3], got [75,4]

```
The output from curl -v localhost:8080/api/status for the model looks as follows.

```
max_batch_size: 1
input {
name: “image:0”
data_type: TYPE_FP32
dims: -1
dims: 3
}
output {
name: “output/scores:0”
data_type: TYPE_FP32
dims: 1
reshape {
}
}
output {
name: “output/labels:0”
data_type: TYPE_INT64
dims: 1
reshape {
}
}
output {
name: “output/boxes:0”
data_type: TYPE_FP32
dims: 4
}
```
Any help will be appreciated.

**Triton Information**
latest  container on nvcr

Are you using the Triton container or did you build it yourself?
latest container on nvcr 

**To Reproduce**

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Shouild not crash.

**Comment by CoderHam** [comment]
This is a model specific failure. Can you confirm that the model runs successfully with the same input outside the Triton Server?

**Comment by whatdhack** [comment]
The exact same model  ( Tensorflow Saved Model ) has been running without any issue in Tensorflow Serving server.   How do I debug this to the next level ?

**Comment by deadeyegoodwin** [comment]
What version of TF did you use to create the saved-model and what version of Triton are you using. TF saved-model is usually backward compatible but sometimes not... so if the version of TF in Triton does not match that may be a problem.

**Comment by whatdhack** [comment]
Model created on 1.14 -  running on TF 1.15 Tensorflow Serving  currently.

Triton - nvcr.io/nvidia/tritonserver:20.03-py3 .

**Comment by deadeyegoodwin** [comment]
The error is happening in the model and its interaction with the cudnn library.

Can you try running the model using the 20.03 release of the TensorFlow container on ngc.nvidia.com? That TensorFlow will match what is in Triton 20.03. Alternatively you can look in the Triton release notes and find the Triton version that used TF 1.14 and try using that with your model.

**Comment by whatdhack** [comment]
TF 1.15.0 was released on 10/26/2019.  Tried all the Inference Sever containers upto September ( e.g. nvcr.io/nvidia/tensorrtserver:19.09-py3 to nvcr.io/nvidia/tensorrtserver:20.02-py3) . Same core dump issue manifested   in all of them.

**Comment by whatdhack** [comment]
I think I figured out the issue.  The model input is (?,?,3) .  Works with straight TF (all versions I tried)  - as it allows np arrays as input. In the Trinton Python client SDK however,  the input has to be a list  and that increases the Tensor rank by 1. So what I  did was reshaped the  array  to (-1,3) to make the client happy - that causes TF to core dump as the model gets  input of incoorect rank (e.g. (?,3) instead of (?,?,3) )

What is the way to feed a straight np array instead of a list  in the Triton Python SDK client ?  Converting an np array to a  list would be an unecessary expensive operation.  Raw Rest API may be a better option here.  Where do I find spec/sample for that. Any suggestion will be appreciates. 



When numpy array is used as input:
```
tensorrtserver.api.InferenceServerException: [ 0] input 'image:0' values must be specified as a list of numpy arrays or as a single c_void_p (representing the shared memory handle) or as a tuple of c_void_p (representing the shared memory handle) and list (representing the shape of the input tensor)
```
When  included in a list:

```
tensorrtserver.api.InferenceServerException: [inference:0 10] unexpected shape for input 'image:0' for model 'xxxxxx'. Expected [-1,3], got [960,540,3]
```

**Comment by whatdhack** [comment]
I think the main problem is how Triton changes the tensor shape - from (?,?,3) to (?,3) etc .  For comparion see the output from  Triton Status call and saved_model_cli. 

saved_model_cli  output:
```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image:0'] tensor_info:
        **dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: image:0**
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output/boxes:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: output/boxes:0
    outputs['output/labels:0'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: output/labels:0
    outputs['output/scores:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: output/scores:0
  Method name is: tensorflow/serving/predict
```

Triton Status call:
```
      max_batch_size: 1
      input {
        name: "image:0"
        data_type: TYPE_FP32
        dims: -1
        dims: 3
      }
      output {
        name: "output/scores:0"
        data_type: TYPE_FP32
        dims: 1
        reshape {
        }
      }
      output {
        name: "output/labels:0"
        data_type: TYPE_INT64
        dims: 1
        reshape {
        }
      }
      output {
        name: "output/boxes:0"
        data_type: TYPE_FP32
        dims: 4
      }
```

**Comment by deadeyegoodwin** [comment]
I think there are a couple of misunderstandings going on if I understand what you are saying. First, in the model configuration file, if you set max_batch_size > 0 then you are telling Triton that every input and output has a first dimension that is acting as the batch dimension. So in your model configuration above you are telling Triton that image:0 has shape [ -1, -1, 3 ] and output/boxes:0 has shape [ -1, 4 ].  Read this section carefully: https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/model_configuration.html#model-configuration

In the client you use a list to send in a batch of inputs. If you are not batching your list should have only 1 entry. So, when sending a batch you don't combine the individual batch entries into a single large numpy array. This is done intentionally to avoid users having to create a combined numpy array for a batched input when they have individual numpy arrays for each batch entry.

**Comment by whatdhack** [comment]
Well,  this is what I followed from that page. 

```
TensorFlow SavedModel models do not require a model configuration file because the inference server can derive all the required settings automatically.
```

 If you think  specifying a model config  file should fix that, I can try that out.

**Comment by deadeyegoodwin** [comment]
Your comment that shows the signature_def and corresponding model configuration looks to be correct. If that model configuration was generated with --strict-model-config=false then it looks like Triton is doing the right thing there. I guess I don't understand your issue. Perhaps you are using the client API incorrectly. Can you show the shape of the numpy array(s) and how you are passing them to the Python API.

**Comment by whatdhack** [comment]
Here is the client code 

```

ctx = InferContext(url, protocol, model_name,  model_version, verbose, 0, False)
input_batch = []  

# the reshape in the following is incorrect for the model , but that is the only shape Trinton likes for this model
input_image1 = (np.random.random_sample((1333,750,3))*100).reshape((-1,3)).astype(np.float32)

input_batch.append(input_image1)
input_name = 'image:0'

results = ctx.run({ 'image:0' : input_batch}, # input_batch has to be a list, not a np array.
                  { 'output/scores:0' : InferContext.ResultFormat.RAW,
                    'output/labels:0' : InferContext.ResultFormat.RAW,
                    'output/boxes:0'  : InferContext.ResultFormat.RAW,
                  },
                    batch_size=batch_size)

print ( "result: ", result)

```

**Comment by deadeyegoodwin** [comment]
I assume you image is HWC? I think I see the problem. The --strict-model-config thought that the first dimension was a batch dimension because it was -1 for all the inputs/outputs. But I don't think it is... I think the model does not support batching. Try creating a config.pbtxt that contains just "max_batch_size=0". The run with --strict-model-config=false and it should generate a config assuming the model doesn't support batching.

When you are writing the client code forget that you know the details of the model. From the model config the shape of each input tells you the shape that you need for you numpy (that is, no batch dimension). The maximum number of numpys that you can put in 'input_batch' is determine by max_batch_size (with the exception that for max_batch_size==0 you can have exactly 1 numpy in 'input_batch').

I think the original confusion is from the config.pbtxt being generated assuming batching when that is not the case.

**Comment by whatdhack** [comment]
That seems to work.  The config.pbtxt follows.  Also enabled FP16 - did not see any improvement in end-to-end processing time though. In fact, it worsened by 10-15%.   Wondering if the following is correct.  
I see 2 different syntaxes for dims - one is as follows and the other  has the form [-1, -1, 3] . What is the difference for ? 
```
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
        {
        name: "image:0"
        data_type: TYPE_FP32
        dims:  -1
        dims:  -1
        dims:   3
      }
]
output [
        {
        name: "output/boxes:0"
        data_type: TYPE_FP32
        dims: -1
        dims:  4
      },
      {
        name: "output/scores:0"
        data_type: TYPE_FP32
        dims: -1
      },
      {
        name: "output/labels:0"
        data_type: TYPE_INT64
        dims: -1
      }
]
optimization                                                
{ execution_accelerators {                                  
   gpu_execution_accelerator : [ {                          
     name : "tensorrt"                                      
     parameters { key: "precision_mode" value: "FP16" }}]   
}}                                                          
```

See the following  output at start.

```
2020-04-15 06:44:04.113328: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:460] There are 1070 ops of 6 different types in the graph that are not converted to TensorRT: Assi

gn, RestoreV2, PlaceholderWithDefault, Const, NoOp, VariableV2, (For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-op

s).
2020-04-15 06:44:04.113758: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:633] Number of TensorRT candidate segments: 0
2020-04-15 06:44:04.785002: I tensorflow/cc/saved_model/loader.cc:332] SavedModel load for tags { serve }; Status: success. Took 17675592 microseconds.
I0415 06:44:04.785522 943 dynamic_batch_scheduler.cc:233] Starting dynamic-batch scheduler thread 0 at nice 5...
I0415 06:44:04.785565 943 base_backend.cc:127] backend for XXXXXXXX
```

**Comment by deadeyegoodwin** [comment]
The different dims syntax is just a protobuf feature. You can represent array either way in protobuf text format.

From your log it looks like TensorRT did not optimize any of your graph because it did not recognized a lot of the operations. You can look at the mentioned link to find more information but if you want more help with TensorRT integration into TF you should ask here: https://github.com/NVIDIA/TensorRT/issues.

It seems like your Triton issue is resolved so I am closing.

**Comment by whatdhack** [comment]
Sure, will post there also.  The complete log follows. Let me know if you see anything glaring. 

```
x, Where, MatMul, CropAndResize, GatherNd, Fill, Greater, Sub, Tile, Cast, TopKV2, NonMaxSuppressionV3, Identity, VariableV2, ReverseV2, ExpandDims, FusedBatchNorm, MirrorPad, GatherV2, NoOp, ConcatV2, Placeholder, Minimum, StridedSlice, Reshape, Add, Squeeze, BiasAdd, Shape, Pack, Transpose, RealDiv, Slice, Conv2D, Size, (For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops).
2020-04-16 16:20:55.091690: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node TRTEngineOp_0 added for segment 0 consisting of 30 nodes succeeded.
2020-04-16 16:20:55.091836: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node TRTEngineOp_2 added for segment 2 consisting of 8 nodes succeeded.
2020-04-16 16:20:55.091954: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node decode_bbox_target/TRTEngineOp_4 added for segment 4 consisting of 22 nodes succeeded.
2020-04-16 16:20:55.092023: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node decode_bbox_target_1/TRTEngineOp_5 added for segment 5 consisting of 22 nodes succeeded.
2020-04-16 16:20:55.092170: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node TRTEngineOp_6 added for segment 6 consisting of 10 nodes succeeded.
ed.
ed.
2020-04-16 16:20:55.092336: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node group3/block0/TRTEngineOp_9 added for segment 9 consisting of 5 nodes succeeded.
2020-04-16 16:20:55.092385: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node TRTEngineOp_10 added for segment 10 consisting of 7 nodes succeeded.
2020-04-16 16:20:55.092434: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node TRTEngineOp_11 added for segment 11 consisting of 6 nodes succeeded.
gment 12 consisting of 4 nodes succeeded.
d on function objects.
2020-04-16 16:20:55.109708: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.110594: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.112029: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.112930: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.113733: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.114452: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.115815: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.116887: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.118755: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.119809: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.120499: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.121172: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-04-16 16:20:55.402649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-16 16:20:55.644534: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for TRTEngineOp_2 input shapes: [[1,960,540,3]]
2020-04-16 16:20:55.644622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.7
2020-04-16 16:20:55.645130: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.7
2020-04-16 16:20:55.645130: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.7
2020-04-16 16:20:57.004705: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:20:57.005034: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-16 16:20:57.305480: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for TRTEngineOp_3 input shapes: [[1,64,480,270]]
@@@
2020-04-16 16:20:57.895732: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:20:58.340652: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for group1/block0/TRTEngineOp_7 input shapes: [[1,128,240,135]]
2020-04-16 16:20:58.405655: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:20:58.699315: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for group2/block0/TRTEngineOp_8 input shapes: [[1,256,120,67]]
2020-04-16 16:20:58.757496: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:20:59.408881: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for decode_bbox_target/TRTEngineOp_4 input shapes: [[29700,2,2], [29700,2,2]]
@@@
2020-04-16 16:20:59.543261: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:20:59.544875: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for TRTEngineOp_0 input shapes: [[1000,4]]
I0416 16:20:59.550411 199 server.cc:224] Polling model repository
2020-04-16 16:20:59.750188: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:20:59.750575: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for roi_align/crop_and_resize/transform_fpcoor_for_tf/TRTEngineOp_12 input shapes: [[1000,1], [1000,1], [1000,1], [1000,1]]
@@@
2020-04-16 16:20:59.779093: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:20:59.779381: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for TRTEngineOp_10 input shapes: [[1000,28,28,1024]]
I0416 16:21:14.550869 199 server.cc:224] Polling model repository
I0416 16:21:29.551246 199 server.cc:224] Polling model repository
2020-04-16 16:21:33.189718: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:21:34.870265: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for group3/block0/TRTEngineOp_9 input shapes: [[1000,512,14,14]]
2020-04-16 16:21:35.235690: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:21:39.709996: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for TRTEngineOp_6 input shapes: [[1000,2048,7,7], [1000,2048,7,7]]
2020-04-16 16:21:41.255460: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:21:41.255819: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for TRTEngineOp_1 input shapes: [[1000,56]]
2020-04-16 16:21:41.255903: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for TRTEngineOp_11 input shapes: [[1000,14]]
2020-04-16 16:21:41.299566: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:21:41.301971: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2020-04-16 16:21:41.302086: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:733] Building a new TensorRT engine for decode_bbox_target_1/TRTEngineOp_5 input shapes: [[14000,2,2], [14000,2,2]]
2020-04-16 16:21:41.437978: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
I0416 16:21:41.438855 199 base_backend.cc:573] output 'output/boxes:0' is GPU tensor: 0
I0416 16:21:41.438892 199 http_server.cc:434] HTTP allocation: 'output/boxes:0', size: 1248, addr: 0x7ff391a0d9c0
I0416 16:21:41.438909 199 base_backend.cc:573] output 'output/labels:0' is GPU tensor: 0
I0416 16:21:41.438923 199 http_server.cc:434] HTTP allocation: 'output/labels:0', size: 624, addr: 0x7ff4a26fe7f0
I0416 16:21:41.438931 199 base_backend.cc:573] output 'output/scores:0' is GPU tensor: 0
I0416 16:21:41.438941 199 http_server.cc:434] HTTP allocation: 'output/scores:0', size: 312, addr: 0x7ff4a27092b0
I0416 16:21:41.439635 199 http_server.cc:445] HTTP release: size 1248, addr 0x7ff391a0d9c0
I0416 16:21:41.439649 199 http_server.cc:445] HTTP release: size 624, addr 0x7ff4a26fe7f0
I0416 16:21:41.439654 199 http_server.cc:445] HTTP release: size 312, addr 0x7ff4a27092b0
I0416 16:21:41.450240 199 http_server.cc:456] HTTP request: 2 /api/infer/xxxx
I0416 16:21:41.450305 199 model_repository_manager.cc:511] GetInferenceBackend() 'xxxx' version -1
I0416 16:21:41.450374 199 base_backend.cc:643] Running xxxx_0_gpu0 with 1 request payloads
I0416 16:21:41.450481 199 base_backend.cc:455] input 'image:0' is GPU tensor: 0
I0416 16:21:44.454070 199 base_backend.cc:573] output 'output/boxes:0' is GPU tensor: 0
I0416 16:21:44.454109 199 http_server.cc:434] HTTP allocation: 'output/boxes:0', size: 1248, addr: 0x7ff391a0d9c0
I0416 16:21:44.454119 199 base_backend.cc:573] output 'output/labels:0' is GPU tensor: 0
I0416 16:21:44.454125 199 http_server.cc:434] HTTP allocation: 'output/labels:0', size: 624, addr: 0x7ff4a26fd870
I0416 16:21:44.454132 199 base_backend.cc:573] output 'output/scores:0' is GPU tensor: 0
I0416 16:21:44.454142 199 http_server.cc:434] HTTP allocation: 'output/scores:0', size: 312, addr: 0x7ff4a26f7e70
I0416 16:21:44.454242 199 http_server.cc:445] HTTP release: size 1248, addr 0x7ff391a0d9c0
I0416 16:21:44.454253 199 http_server.cc:445] HTTP release: size 624, addr 0x7ff4a26fd870
I0416 16:21:44.454257 199 http_server.cc:445] HTTP release: size 312, addr 0x7ff4a26f7e70
I0416 16:21:44.462411 199 http_server.cc:456] HTTP request: 2 /api/infer/xxxx
I0416 16:21:44.462473 199 model_repository_manager.cc:511] GetInferenceBackend() 'xxxx' version -1
I0416 16:21:44.462526 199 base_backend.cc:643] Running xxxx_0_gpu0 with 1 request payloads
```
