### ISSUE TITLE
Core dump when all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by mvpel** [NVIDIA/triton-inference-server#1321]
**Description**
Running Triton within NVIDIA-supplied container results in core dump at startup.

After security hardening was performed this afternoon, the Triton server container stopped working.

>  /opt/tensorrtserver/bin/trtserver --model-repository=/triton.repos.d --strict-model-config=false --repository-poll-secs=120
> 2020-04-16 16:04:11.897747: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
> I0416 20:04:12.365805 69759 metrics.cc:164] found 2 GPUs supporting NVML metrics
> I0416 20:04:12.371289 69759 metrics.cc:173]   GPU 0: Tesla T4
> I0416 20:04:12.376856 69759 metrics.cc:173]   GPU 1: Tesla T4
> I0416 20:04:12.376948 69759 server.cc:120] Initializing Triton Inference Server
> **E0416 20:04:12.388024 69759 pinned_memory_manager.cc:194] failed to allocate pinned system memory: all CUDA-capable devices are busy or unavailable**
> E0416 20:04:12.389103 69759 server.cc:138] failed to enable peer access for some device pairs
> 2020-04-16 16:04:12.395290: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /triton.repos.d/TR46_InceptionNet_FFS_300ep0.6train_5classes_noshuffle/3/model.savedmodel
> 2020-04-16 16:04:12.442681: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
> 2020-04-16 16:04:12.536376: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3300000000 Hz
> 2020-04-16 16:04:12.537742: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x556ae73c4ab0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-04-16 16:04:12.537766: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-04-16 16:04:12.537956: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> **2020-04-16 16:04:12.538743: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_VALUE: invalid argument**
> **Aborted (core dumped)**

At first I thought this was an issue with the memlock limit in /etc/security/limits.conf, but that hadn't changed, and I set it to unlimited to no avail.

The NVIDIA driver is installed and the latest version, and the nvidia-smi command works as expected:

```
Thu Apr 16 16:18:27 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:5E:00.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |     11MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:AF:00.0 Off |                    0 |
| N/A   33C    P8     9W /  70W |     11MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

While I know it's incumbent upon me to determine why the security hardening appears to have broken Triton (though any suggestions would be welcome), we'll want to make sure that a core dump is not the outcome of unexpected situations.

**Triton Information**
20.03 Triton container

I'll update this once I can figure out what system setting changed this afternoon to cause the failure.

**Comment by mvpel** [comment]
Here's the backtrace from the core file:

[triton-backtrace.txt](https://github.com/NVIDIA/triton-inference-server/files/4489610/triton-backtrace.txt)

**Comment by mvpel** [comment]
Turns out the problem is that the GDM desktop manager had grabbed both GPU cards for itself at boot-up. I did a systemctl disable gdm, and that fixed the problem. Apparently the security hardening scripts re-enabled GDM while configuring the screen saver lock timeout.

**Comment by abdulsamadzahir** [comment]
> Turns out the problem is that the GDM desktop manager had grabbed both GPU cards for itself at boot-up. I did a systemctl disable gdm, and that fixed the problem. Apparently the security hardening scripts re-enabled GDM while configuring the screen saver lock timeout.

This solved the problem for me too on Ubuntu 18.04 and an RTX 2080 Ti. The system was working fine before hibernating. After resuming (and going into screen saver lock timeout), my code would not run.

Just for reference, I was getting this error:

> tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable

Running this command on terminal solved the issue:
`systemctl disable gdm`
